Promise.all([
    module.shareImport('uppercases.js'),
    module.shareImport('lowercases.js'),
]).then(modules=>{
    let
        uppercases=modules[0],
        lowercases=modules[1]
    function lt(vim,cmd,arg){
        if(cmd=='')
            return{acceptable:true}
        if(cmd=='<'){
            return{
                acceptable:true,
                complete:true,
                changed:true,
            }
        }
    }
    function gt(vim,cmd,arg){
        if(cmd=='')
            return{acceptable:true}
        if(cmd=='>'){
            let
                a=vim._cursor.lineStart,
                b=vim._cursor.lineEnd
            vim._text=
                vim._text.substring(0,a)+
                '\t'+
                vim._text.substring(a,b)+
                vim._text.substring(b)
            return{
                acceptable:true,
                complete:true,
                changed:true,
            }
        }
    }
    function dot(vim,cmd,arg){
        return{
            acceptable:true,
            complete:true,
        }
    }
    function colon(vim){
        vim.mode='cmdline'
        vim._modeData.inputBuffer=':'
        vim._modeData.cursor.position=1
        return{acceptable:true}
    }
    function slash(vim){
        vim.mode='cmdline'
        vim._modeData.inputBuffer='/'
        vim._modeData.cursor.position=1
        return{acceptable:true}
    }
    function ctrl(vim,cmd){
        if(cmd=='')
            return{
                acceptable:true,
            }
        if(cmd=='r'){
            if(vim._undoBranchManager.current.next!=undefined){
                vim._undoBranchManager.current=
                    vim._undoBranchManager.current.next
                vim._text=vim._undoBranchManager.current.text
            }
            return{
                acceptable:true,
                complete:true,
            }
        }
    }
    let commands={
        A:uppercases.A,
        D:uppercases.D,
        G:uppercases.G,
        I:uppercases.I,
        O:uppercases.O,
        P:uppercases.P,
        X:uppercases.X,
        a:lowercases.a,
        d:lowercases.d,
        g:lowercases.g,
        h:lowercases.h,
        i:lowercases.i,
        j:lowercases.j,
        k:lowercases.k,
        l:lowercases.l,
        n:lowercases.n,
        o:lowercases.o,
        p:lowercases.p,
        r:lowercases.r,
        u:lowercases.u,
        v:lowercases.v,
        x:lowercases.x,
        y:lowercases.y,
        '<':lt,
        '>':gt,
        '.':dot,
        ':':colon,
        '/':slash,
    }
    commands[String.fromCharCode(17)]=ctrl
    return commands
})
