import doe from'../../../../../../lib/doe.mjs'
import measureWidth from '../../measureWidth.js'
export default ui=>doe.textarea({className:'input'},n=>{
    n.style.fontSize=`${ui._fontSize}px`
    n.style.height=`${ui._fontSize+2}px`
    let
        vim=ui._vim,
        composing=false
    n.addEventListener('blur',()=>{
        vim._ui()
    })
    n.addEventListener('compositionstart',e=>{
        composing=true
    })
    n.addEventListener('compositionend',e=>{
        composing=false
        f()
    })
    n.addEventListener('focus',()=>{
        vim._ui()
    })
    n.addEventListener('input',()=>{
        f()
    })
    n.addEventListener('keydown',e=>{
        if(composing||!(
            e.key=='ArrowLeft'||
            e.key=='ArrowRight'||
            e.key=='ArrowDown'||
            e.key=='ArrowUp'||
            e.key=='Backspace'||
            e.key=='Delete'||
            e.key=='End'||
            e.key=='Enter'||
            e.key=='Escape'||
            e.key=='Home'||
            e.key=='Tab'||
            e.ctrlKey&&e.key=='c'||
            e.ctrlKey&&e.key=='['||
            e.ctrlKey&&e.key=='r'
        ))
            return
        e.preventDefault()
        e.stopPropagation()
        vim.input=e
    })
    function f(){
        if(composing){
            vim._ui()
        }else{
            vim.input=n.value
            n.value=''
        }
        let width=measureWidth(ui._fontSize,n.value)
        if(width)
            width+=2
        n.style.width=`${width}px`
    }
})
