(function createInput(vim){
    let
        input=document.createElement('input')
    input.style.position='absolute'
    input.style.fontFamily='monospace'
    input.style.border=0
    input.style.padding=0
    input.style.fontSize=`${vim.lineHeightInPx}px`
    input.style.backgroundColor='rgba(0,0,0,0)'
    //input.style.height=0
    let
        composing=false
    input.addEventListener('blur',()=>{
        vim.view()
    })
    input.addEventListener('compositionstart',e=>{
        composing=true
    })
    input.addEventListener('compositionend',e=>{
        vim.imInput=''
        composing=false
    })
    input.addEventListener('focus',()=>{
        vim.view()
    })
    input.addEventListener('input',()=>{
        if(composing)
            vim.imInput=input.value
        else{
            vim.command+=input.value
            input.value=''
        }
        if(vim.mode==1)
            vim.view()
    })
    input.addEventListener('keydown',e=>{
        if(
            e.key=='Escape'||
            e.ctrlKey&&e.key=='c'||
            e.ctrlKey&&e.key=='['
        ){
            pdsp()
            vim.command+=String.fromCharCode(27)
        }
        if(
            e.key=='Backspace'
        ){
            pdsp()
            vim.command+=String.fromCharCode(8)
        }
        function pdsp(){
            e.preventDefault()
            e.stopPropagation()
        }
    })
    return input
})
